---
output: 
  word_document:
    reference_docx: ../report_template_v1.5.dotx
---

```{r setup, echo=FALSE, fig.asp=1.0, fig.align="center", message=FALSE, warning=FALSE}

# =======================================================================================
# ARU forecast
# 
# 21/04/2020 First coding; adapted from WGWIDE code
# 25/04/2021 Fully adapted to inclusion of plots for WGDEEP report
# =======================================================================================

# devtools::install_github("fishfollower/SAM/stockassessment")

# try(if(packageVersion("stockassessment")=="0.5.4") stop("wrong version of Stockassessment package"))

require("knitr")
knitr::opts_chunk$set(echo = FALSE,	message = FALSE,	warning = FALSE,	comment = "",	crop = TRUE )
knitr::opts_chunk$set(fig.width=10) 

rm(list=ls())

# library(devtools)
library(tidyverse)    # tidying packages
library(readxl)       # read excel
library(scales)
library(RColorBrewer)
library(viridis)
library(pander)
library(stockassessment)
library(ggrepel)

# devtools::install_github("einarhjorleifsson/readsam")
library(readsam)

# lowcase function
source("lowcase.r")
source("theme_publication.r")
source("sam_process_error.r")

# Function to download fit from web to local computer
getfitfromweb <- function(nam){
  dir.create(file.path(nam))
  download.file(file.path("https://www.stockassessment.org/datadisk/stockassessment/userdirs/user233",
                          nam, "run","model.RData"), file.path(nam, "model.RData"))
  load(file.path(nam, "model.RData"))
  return(fit)
  }
# getfitfromweb(nam="WGDEEP_2020")

getparsfromfit <- function(fit) {
  # a  <- gsub("fit_", "", fit) 
  df <- 
    data.frame(stockassessment::partable(fit)) %>% 
    add_rownames() %>%  
    separate(rowname, into=c("parameter", "parnumber"), sep="_")
  return(df)
}


nam         <- "ARU.27.5b6a_WGDEEP_2021"
# assessments <- c("ARU.27.5b6a_WGDEEP_2020_", "ARU.27.5b6a_WGDEEP_2021", "Aru.27.5b6a_wgdeep2021_trial_deepsurv")
assessments <- nam
user        <- "user233"
web         <- TRUE

rp          <- data.frame(var      = c("fbar","ssb","ssb"),
                          refpoint = c("fmsy","blim","msybtrigger"),
                          value    = c(0.2, 59730, 82999))

# read input, results and parameter data
ibya <- rbya <- rby <- pars <- pe_rby <- pe_rbya <- data.frame()
for (a in assessments) {
  print(a)
  assign(paste0("fit_", a), getfitfromweb(a))  
  assign(paste0("ibya_",a), mutate(readsam::read_ibya(a, web = web, user = user), file=a))  
  assign(paste0("rbya_",a), mutate(readsam::read_rbya_sam(get(paste0("fit_", a)), get(paste0("ibya_",a))), file=a) )  
  assign(paste0("rby_",a) , mutate(readsam::read_rby_sam(get(paste0("fit_", a)), get(paste0("ibya_",a))), file=a) )
  assign(paste0("pars_",a), mutate(getparsfromfit(get(paste0("fit_", a))), file=a)) 
  t <- sam_process_error(get(paste0("rbya_",a)),plus_group = TRUE, plot_it=FALSE)
  assign(paste0("pe_rbya_",a), mutate(t[[1]], file=a)) 
  assign(paste0("pe_rby_",a), mutate(t[[2]], file=a)) 
  
  ibya <- bind_rows(ibya, get(paste0("ibya_",a)))
  rbya <- bind_rows(rbya, get(paste0("rbya_",a)))
  rby  <- bind_rows(rby, get(paste0("rby_",a)))
  pars <- bind_rows(pars, get(paste0("pars_",a)))
  pe_rbya <- bind_rows(pe_rbya, get(paste0("pe_rbya_",a)))
  pe_rby  <- bind_rows(pe_rby, get(paste0("pe_rby_",a)))
}

# identical(fit_ARU.27.5b6a_WGDEEP_2020_, fit_ARU.27.5b6a_WGDEEP_2021)
pars <- pars %>% mutate(parnumber = factor(parnumber, levels=unique(.$parnumber))) %>% lowcase()

# several aspects of fit object
fit    <- fit_ARU.27.5b6a_WGDEEP_2021
conf   <- fit$conf
sd     <- fit$pl
data   <- fit$data
ages   <- conf$minAge:conf$maxAge
fleets <- 1:nrow(conf$keyLogFsta)
years  <- data$years
nr     <- nrow(conf$keyLogFsta)
nc     <- ncol(conf$keyLogFsta)


ass <-
  rby %>% 
    filter(file %in% c("ARU.27.5b6a_WGDEEP_2021")) %>% 
    filter(variable %in% c("ssb","fbar","catch")) %>%
    # filter(variable %in% c("catch")) %>% 
    lowcase() %>% 
    rename(var=variable) %>%
    mutate(source="assessment") %>%
    mutate(year = ifelse(var=="catch", year+1994,year)) 

# observed catch in tonnes
ct <- 
  read.table("ct.dat", skip=5) %>% 
  as.data.frame() %>%
  setNames("obs") %>% 
  mutate(
    obs   = as.numeric(obs),
    source="assessment",
    var   = "catch", 
  ) %>% 
  bind_cols(year=fit$data$years) %>% 
  mutate(year  = as.numeric(year))

```

**Greater argentine in 5b and 6a forecast WGDEEP 2021**

Martin Pastoors, `r format(Sys.time(), '%d/%m/%Y')`


Forecast with catch constraint at 17149 tonnes (total catch from intercatch)

```{r, echo=FALSE, fig.asp=0.8, fig.align="center", message=FALSE, warning=FALSE}

source("fix_forecast.r")

Ry  <- fit$data$years[(length(fit$data$years)-10):(length(fit$data$years)-1)]
fsq <- stockassessment::fbartable(fit)[nrow(fbartable(fit)),1]

ft   <- c(  fsq, 0.000001,   0.2,  0.241,  0.33,     seq(0.01,0.3,0.01) )
labs <- c("Fsq",  "Fzero","Fmsy1","Fmsy2", "Fp0.5",  paste0("F=",as.character(seq(0.01,0.3,0.01))) )

# ft   <- c(  fsq, 0.000001,   0.2,  0.241,  0.33 )
# labs <- c("Fsq",  "Fzero","Fmsy1","Fmsy2", "Fp0.5") 

FC<-list()
fc <- data.frame(stringsAsFactors = FALSE)
for (i in 1:length(ft)) {
  # print(ft[i])
  set.seed(12345)
  FC[[i]] <-forecastx(
      fit,
      catchval = c(17149, 17149, NA, NA, NA),
      # catchval = c(15475, 15475, NA, NA, NA),
      fscale = c(NA, NA, NA, NA, NA),
      fval = c(NA, NA, ft[i], ft[i], ft[i]),
      rec.years = Ry,
      label = labs[i],
      processNoise = FALSE,
      addTSB = TRUE
    )
  fc <-
    bind_rows(
      fc,
      as.data.frame(attributes(FC[[i]])$tab) %>% 
      rownames_to_column(var="year") %>% 
      mutate(
        ft = ft[i], 
        label = labs[i]
      ) %>% 
      tidyr::pivot_longer(names_to="var1", values_to="data", "fbar:median":"tsb:high") %>% 
      tidyr::separate(var1, into=c("var","type"), sep=":") %>% 
      tidyr::pivot_wider(names_from=type, values_from=data)
    )
}


# current year
fc %>% 
  filter(year==2021) %>% 
  filter(label=="Fsq") %>% 
  filter(var != "tsb") %>% 
  mutate(ft = ifelse(label=="Fsq",format(as.numeric(ft), digits=3),ft)) %>% 
  # mutate(value = paste0(median, " (", low,"-", high,")")) %>% 
  # dplyr::select(-median, -low, -high) %>% 
  dplyr::select(-low, -high) %>% 
  pandoc.table(.,
                 style = "simple",
                 split.tables=120, 
                 justify = "right",
                 missing=".")

# forecast
fc %>% 
  mutate(ft = ifelse(label=="Fzero","0.0",ft)) %>% 
  mutate(ft = ifelse(label=="Fsq",format(as.numeric(ft), digits=3),ft)) %>% 
  filter(year %in% c(2022, 2023)) %>% 
  
  # mutate(value = paste0(median, " (", low,"-", high,")")) %>% 
  # dplyr::select(-median, -low, -high) %>% 
  # dplyr::select(-low, -high) %>% 
  
  # mutate(value = paste0(as.integer(median), " (", as.integer(low),"-", as.integer(high),")")) %>% 
  # dplyr::select(-median, -low, -high) %>% 
  
  filter(var %in% c("ssb","catch")) %>%
  mutate(var2 = paste(var,year,sep="_")) %>% 
  dplyr::select(-year, -var) %>% 
  
  tidyr::pivot_wider(names_from=var2, values_from=c(median, low, high)) %>% 
  # dplyr::select(label, ft, catch_2022, ssb_2022, ssb_2023) %>% 
  pandoc.table(.,
               style = "simple",
               split.tables=120, 
               justify = "right",
               missing=".")
  
writexl::write_xlsx(fc, path="ARU.27.5b6a forecast catch constraint.xlsx")

# plot assessment and forecast
fc %>% 
  filter(var %in% c("ssb","fbar","catch")) %>%
  filter(label %in% c("Fmsy1")) %>% 
  mutate(year=as.numeric(year)) %>% 
  rename(estimate=median) %>% 
  mutate(source="forecast") %>% 

  ggplot(aes(x=year,y=estimate)) +
  theme_publication() +
  theme(plot.margin=grid::unit(c(0,0,0,0), "mm")) +

  # reference points
  geom_hline(data=rp, aes(yintercept=value, linetype=refpoint), inherit.aes=FALSE) +
  guides(linetype=FALSE) +
  
  # assessment
  geom_line(data=ass, aes(colour=source)) +
  geom_ribbon(data=ass, aes(ymin=low, ymax=high, fill=source), alpha=0.3) +
  
  # observations
  geom_point(data=ct, aes(x=year,y=obs), inherit.aes = FALSE) +

  # forecast
  geom_line(aes(colour=source)) +
  geom_point(aes(x=year,y=estimate, colour=source), inherit.aes = FALSE) +
  geom_ribbon(aes(ymin=low, ymax=high, fill=source), alpha=0.3) +
  
  expand_limits(y=0) +
  labs(x="", y="", title="First Catch constraint, then Fmsy") +
  facet_wrap(~var, scales="free_y", nrow=1)


```

Forecast with Fsq

```{r, echo=FALSE, fig.asp=0.8, fig.align="center", message=FALSE, warning=FALSE}

source("fix_forecast.r")

Ry  <- fit$data$years[(length(fit$data$years)-10):(length(fit$data$years)-1)]
fsq <- stockassessment::fbartable(fit)[nrow(fbartable(fit)),1]

ft   <- c(  fsq, 0.000001,   0.2,  0.241,  0.33,     seq(0.01,0.3,0.01) )
labs <- c("Fsq",  "Fzero","Fmsy1","Fmsy2", "Fp0.5",  paste0("F=",as.character(seq(0.01,0.3,0.01))) )

# ft   <- c(  fsq, 0.000001,   0.2,  0.241,  0.33 )
# labs <- c("Fsq",  "Fzero","Fmsy1","Fmsy2", "Fp0.5")

FC<-list()
fc <- data.frame(stringsAsFactors = FALSE)
for (i in 1:length(ft)) {
  # print(ft[i])
  set.seed(12345)
  FC[[i]] <-forecastx(
      fit,
      # catchval = c(15475, 15475, NA, NA, NA),
      # catchval = c(15475, 15475, NA, NA, NA),
      fscale = c(NA, NA, NA, NA, NA),
      fval = c(fsq, fsq, ft[i], ft[i], ft[i]),
      rec.years = Ry,
      label = labs[i],
      processNoise = FALSE,
      addTSB = TRUE
    )
  fc <-
    bind_rows(
      fc,
      as.data.frame(attributes(FC[[i]])$tab) %>% 
      rownames_to_column(var="year") %>% 
      mutate(
        ft = ft[i], 
        label = labs[i]
      ) %>% 
      tidyr::pivot_longer(names_to="var1", values_to="data", "fbar:median":"tsb:high") %>% 
      tidyr::separate(var1, into=c("var","type"), sep=":") %>% 
      tidyr::pivot_wider(names_from=type, values_from=data)
    )
}

# current year
fc %>% 
  filter(year==2021) %>% 
  filter(label=="Fsq") %>% 
  filter(var != "tsb") %>% 
  mutate(ft = ifelse(label=="Fsq",format(as.numeric(ft), digits=3),ft)) %>% 
  # mutate(value = paste0(median, " (", low,"-", high,")")) %>% 
  # dplyr::select(-median, -low, -high) %>% 
  # dplyr::select(-low, -high) %>% 
  pandoc.table(.,
                 style = "simple",
                 split.tables=120, 
                 justify = "right",
                 missing=".")

fc %>% 
  mutate(ft = ifelse(label=="Fzero","0.0",ft)) %>% 
  mutate(ft = ifelse(label=="Fsq",format(as.numeric(ft), digits=3),ft)) %>% 
  filter(year %in% c(2022, 2023)) %>% 
  
  # mutate(value = paste0(median, " (", low,"-", high,")")) %>% 
  # dplyr::select(-median, -low, -high) %>% 
  # dplyr::select(-low, -high) %>% 
  
  # mutate(value = paste0(as.integer(median), " (", as.integer(low),"-", as.integer(high),")")) %>% 
  # dplyr::select(-median, -low, -high) %>% 
  
  filter(var %in% c("ssb","catch")) %>%
  mutate(var2 = paste(var,year,sep="_")) %>% 
  dplyr::select(-year, -var) %>% 
  
  tidyr::pivot_wider(names_from=var2, values_from=c(median, low, high)) %>% 
  # dplyr::select(label, ft, catch_2022, ssb_2022, ssb_2023) %>% 
  pandoc.table(.,
               style = "simple",
               split.tables=120, 
               justify = "right",
               missing=".")


writexl::write_xlsx(fc, path="ARU.27.5b6a forecast Fsq.xlsx")


# plot assessment and forecast
fc %>% 
  filter(var %in% c("ssb","fbar","catch")) %>%
  filter(label %in% c("Fmsy1")) %>% 
  mutate(year=as.numeric(year)) %>% 
  rename(estimate=median) %>% 
  mutate(source="forecast") %>% 

  ggplot(aes(x=year,y=estimate)) +
  theme_publication() +
  theme(plot.margin=grid::unit(c(0,0,0,0), "mm")) +

  # reference points
  geom_hline(data=rp, aes(yintercept=value, linetype=refpoint), inherit.aes=FALSE) +
  guides(linetype=FALSE) +
  
  # assessment
  geom_line(data=ass, aes(colour=source)) +
  geom_ribbon(data=ass, aes(ymin=low, ymax=high, fill=source), alpha=0.3) +
  
  # observations
  geom_point(data=ct, aes(x=year,y=obs), inherit.aes = FALSE) +

  # forecast
  geom_line(aes(colour=source)) +
  geom_point(aes(x=year,y=estimate, colour=source), inherit.aes = FALSE) +
  geom_ribbon(aes(ymin=low, ymax=high, fill=source), alpha=0.3) +
  
  expand_limits(y=0) +
  labs(x="", y="", title="First Fsq, then Fmsy") +
  facet_wrap(~var, scales="free_y", nrow=1)



```

```{r, echo=FALSE, fig.asp=0.8, fig.align="center", message=FALSE, warning=FALSE}

# Assessment + forecast

# observed catch in tonnes
ct <- 
  read.table("ct.dat", skip=5) %>% 
  as.data.frame() %>%
  setNames("obs") %>% 
  mutate(
    obs   = as.numeric(obs),
    source="assessment",
    var   = "catch", 
  ) %>% 
  bind_cols(year=fit$data$years) %>% 
  mutate(year  = as.numeric(year))

# forecast
t1 <-
  fc %>% 
    filter(var %in% c("ssb","fbar","catch")) %>%
    # filter(var %in% c("catch")) %>% 
    filter(label %in% c("Fsq", "Fmsy1")) %>% 
    mutate(year=as.numeric(year)) %>% 
    rename(estimate=median) %>% 
    mutate(source="forecast")

plist <- list()
mylabels <- c("Fsq", "Fmsy1")

i <- 1

for (i in 1:length(mylabels)) {
  plist[[i]] <-
    t1 %>% 
    filter(label == mylabels[[i]]) %>% 
    
    ggplot(aes(x=year,y=estimate)) +
    theme_publication() +
    theme(plot.margin=grid::unit(c(0,0,0,0), "mm")) +
    {if(i!=length(mylabels)) theme(legend.position="null") } +   
    
    # reference points
    geom_hline(data=rp, aes(yintercept=value, linetype=refpoint), inherit.aes=FALSE) +
    guides(linetype=FALSE) +
    
    # assessment
    geom_line(data=ass, aes(colour=source)) +
    geom_ribbon(data=ass, aes(ymin=low, ymax=high, fill=source), alpha=0.3) +
    
    # observations
    geom_point(data=ct, aes(x=year,y=obs), inherit.aes = FALSE) +
  
    # forecast
    geom_line(aes(colour=source)) +
    geom_point(aes(x=year,y=estimate, colour=source), inherit.aes = FALSE) +
    geom_ribbon(aes(ymin=low, ymax=high, fill=source), alpha=0.3) +
    
    expand_limits(y=0) +
    labs(x="", y="", title=mylabels[[i]]) +
    facet_wrap(~var, scales="free_y", nrow=1)
}

print(patchwork::wrap_plots(plist) + 
  patchwork::plot_layout(ncol = 1, heights = c(0.5, 0.5)) +
  patchwork::plot_annotation() & theme(plot.tag = element_text(size = 8)))


```

Forecast with catch constraint at 15475 NS (SoP from intercatch ages 5+) and correction factor of 3 years

```{r, echo=FALSE, fig.asp=0.8, fig.align="center", message=FALSE, warning=FALSE}

# observed catch in tonnes
ct <- 
  read.table("ct.dat", skip=5) %>% 
  as.data.frame() %>%
  setNames("obs") %>% 
  mutate(
    obs   = as.numeric(obs),
    source="ic2plus",
    var   = "catch", 
  ) %>% 
  bind_cols(year=fit$data$years) %>% 
  mutate(year  = as.numeric(year))

ct2 <- 
  read.table("ct2.dat", skip=5) %>% 
  as.data.frame() %>%
  setNames("obs") %>% 
  mutate(
    obs   = as.numeric(obs),
    source="ic5plus",
    var   = "catch", 
  ) %>% 
  bind_cols(year=fit$data$years) %>% 
  mutate(year  = as.numeric(year))

# calculate catch factor
catch_factor <-
  bind_rows(ct, ct2) %>% 
  group_by(year) %>%
  pivot_wider(names_from = source, values_from = obs) %>% 
  mutate(factor = ic2plus / ic5plus) %>% 
  ungroup() %>% 
  slice_tail(n=3) %>% 
  summarize(factor=mean(factor, na.rm=TRUE)) %>% 
  as.numeric()

source("fix_forecast.r")

Ry  <- fit$data$years[(length(fit$data$years)-10):(length(fit$data$years)-1)]
fsq <- stockassessment::fbartable(fit)[nrow(fbartable(fit)),1]

ft   <- c(  fsq, 0.000001,   0.2,  0.241,  0.33,     seq(0.01,0.3,0.01) )
labs <- c("Fsq",  "Fzero","Fmsy1","Fmsy2", "Fp0.5",  paste0("F=",as.character(seq(0.01,0.3,0.01))) )

# ft   <- c(  fsq, 0.000001,   0.2,  0.241,  0.33 )
# labs <- c("Fsq",  "Fzero","Fmsy1","Fmsy2", "Fp0.5") 

FC<-list()
fc <- data.frame(stringsAsFactors = FALSE)
for (i in 1:length(ft)) {
  # print(ft[i])
  set.seed(12345)
  FC[[i]] <-forecastx(
      fit,
      catchval = c(15475, 15475, NA, NA, NA),
      # catchval = c(15475, 15475, NA, NA, NA),
      fscale = c(NA, NA, NA, NA, NA),
      fval = c(NA, NA, ft[i], ft[i], ft[i]),
      rec.years = Ry,
      label = labs[i],
      processNoise = FALSE,
      addTSB = TRUE
    )
  fc <-
    bind_rows(
      fc,
      as.data.frame(attributes(FC[[i]])$tab) %>% 
      rownames_to_column(var="year") %>% 
      mutate(
        ft = ft[i], 
        label = labs[i]
      ) %>% 
      tidyr::pivot_longer(names_to="var1", values_to="data", "fbar:median":"tsb:high") %>% 
      tidyr::separate(var1, into=c("var","type"), sep=":") %>% 
      tidyr::pivot_wider(names_from=type, values_from=data)
    )
}

# adapt catches with factor
fc2 <- 
  fc %>% 
  mutate(
    median = ifelse(var=="catch", median * catch_factor, median),
    low    = ifelse(var=="catch", low * catch_factor, low),
    high = ifelse(var=="catch", high * catch_factor, high)
  )
  
# current year
fc2 %>% 
  filter(year==2021) %>% 
  filter(label=="Fsq") %>% 
  filter(var != "tsb") %>% 
  mutate(ft = ifelse(label=="Fsq",format(as.numeric(ft), digits=3),ft)) %>% 
  mutate(value = paste0(median, " (", low,"-", high,")")) %>% 
  dplyr::select(-median, -low, -high) %>% 
  pandoc.table(.,
                 style = "simple",
                 split.tables=120, 
                 justify = "right",
                 missing=".")

# forecast
fc2 %>% 
  mutate(ft = ifelse(label=="Fzero","0.0",ft)) %>% 
  mutate(ft = ifelse(label=="Fsq",format(as.numeric(ft), digits=3),ft)) %>% 
  filter(year %in% c(2022, 2023)) %>% 
  
  mutate(value = paste0(as.integer(median), " (", as.integer(low),"-", as.integer(high),")")) %>% 
  dplyr::select(-median, -low, -high) %>% 
  
  filter(var %in% c("ssb","catch")) %>%
  mutate(var2 = paste(var,year,sep="_")) %>% 
  dplyr::select(-year, -var) %>% 
  
  tidyr::pivot_wider(names_from=var2, values_from=value) %>% 
  dplyr::select(label, ft, catch_2022, ssb_2022, ssb_2023) %>% 
  pandoc.table(.,
               style = "simple",
               split.tables=120, 
               justify = "right",
               missing=".")
  



```


```{r, echo=FALSE, fig.asp=0.8, fig.align="center", message=FALSE, warning=FALSE}

# Assessment + forecast

# observed catch in tonnes
ct2 <- 
  read.table("ct2.dat", skip=5) %>% 
  as.data.frame() %>%
  setNames("obs") %>% 
  mutate(
    obs   = as.numeric(obs),
    source="assessment",
    var   = "catch", 
  ) %>% 
  bind_cols(year=fit$data$years) %>% 
  mutate(year  = as.numeric(year))

# forecast
t1 <-
  fc2 %>% 
    filter(var %in% c("ssb","fbar","catch")) %>%
    # filter(var %in% c("catch")) %>% 
    filter(label %in% c("Fsq", "Fmsy1")) %>% 
    mutate(year=as.numeric(year)) %>% 
    rename(estimate=median) %>% 
    mutate(source="forecast")

plist <- list()
mylabels <- c("Fsq", "Fmsy1")

i <- 1

for (i in 1:length(mylabels)) {
  plist[[i]] <-
    t1 %>% 
    filter(label == mylabels[[i]]) %>% 
    
    ggplot(aes(x=year,y=estimate)) +
    theme_publication() +
    theme(plot.margin=grid::unit(c(0,0,0,0), "mm")) +
    {if(i!=length(mylabels)) theme(legend.position="null") } +   
    
    # reference points
    geom_hline(data=rp, aes(yintercept=value, linetype=refpoint), inherit.aes=FALSE) +
    guides(linetype=FALSE) +
    
    # assessment
    geom_line(data=ass, aes(colour=source)) +
    geom_ribbon(data=ass, aes(ymin=low, ymax=high, fill=source), alpha=0.3) +
    
    # observations
    geom_point(data=ct, aes(x=year,y=obs), inherit.aes = FALSE) +
  
    # forecast
    geom_line(aes(colour=source)) +
    geom_point(aes(x=year,y=estimate, colour=source), inherit.aes = FALSE) +
    geom_ribbon(aes(ymin=low, ymax=high, fill=source), alpha=0.3) +
    
    expand_limits(y=0) +
    labs(x="", y="", title=mylabels[[i]]) +
    facet_wrap(~var, scales="free_y", nrow=1)
}

print(patchwork::wrap_plots(plist) + 
  patchwork::plot_layout(ncol = 1, heights = c(0.5, 0.5)) +
  patchwork::plot_annotation() & theme(plot.tag = element_text(size = 8)))


```
